### ISSUE TITLE
missing python dependencies

### ISSUE THREAD

**Issue by rhs** [datawire/kubernaut#1]
I hit some trouble. I was doing all this in a python 2.7 virtualenv. Would be good to list what python version you expect.

I followed the pip install instructions and ended up with some broken imports:
  ImportError: No module named requests

After installing requests manually, I get this:
  ImportError: No module named pathlib

After manually installing pathlib, I get this:

Traceback (most recent call last):
  File "/home/rhs/.virtualenvs/kubernaut/bin/kubernaut", line 11, in <module>
    load_entry_point('kubernaut==0.1.0', 'console_scripts', 'kubernaut')()
  File "/home/rhs/.virtualenvs/kubernaut/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rhs/.virtualenvs/kubernaut/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2652, in load_entry_point
    return ep.load()
  File "/home/rhs/.virtualenvs/kubernaut/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in load
    return self.resolve()
  File "/home/rhs/.virtualenvs/kubernaut/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rhs/.virtualenvs/kubernaut/lib/python2.7/site-packages/kubernaut/cli.py", line 15, in <module>
    config_root = Path.home() / ".config" / "kubernaut"
AttributeError: type object 'Path' has no attribute 'home'

**Comment by plombardi89** [comment]
Requires Python 3 and not Python 2. I'll make sure this is called out at some point in the future.
