### ISSUE TITLE
kubernaut 0.1.40 can't set-token with Python 3

### ISSUE THREAD

**Issue by kflynn** [datawire/kubernaut#32]
```$ kubernaut set-token (jwt-elided)
Traceback (most recent call last):
  File "/Users/flynn/datawire/a2/end-to-end/kubernaut/.bootstrap/_pex/pex.py", line 365, in execute
  File "/Users/flynn/datawire/a2/end-to-end/kubernaut/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/Users/flynn/datawire/a2/end-to-end/kubernaut/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/Users/flynn/datawire/a2/end-to-end/kubernaut/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/Users/flynn/datawire/a2/end-to-end/kubernaut/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/Users/flynn/datawire/a2/end-to-end/kubernaut/.bootstrap/_pex/pex.py", line 484, in execute_pkg_resources
  File "/Users/flynn/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/flynn/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/flynn/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/flynn/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/flynn/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/flynn/.pex/install/kubernaut-0.1.40-py3-none-any.whl.dec8a4facc843eaf3ac6b5906a6d908ba8d1c452/kubernaut-0.1.40-py3-none-any.whl/kubernaut/cli.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/Users/flynn/.pex/install/kubernaut-0.1.40-py3-none-any.whl.dec8a4facc843eaf3ac6b5906a6d908ba8d1c452/kubernaut-0.1.40-py3-none-any.whl/kubernaut/cli.py", line 221, in cli_set_token
    save_config(config)
  File "/Users/flynn/.pex/install/kubernaut-0.1.40-py3-none-any.whl.dec8a4facc843eaf3ac6b5906a6d908ba8d1c452/kubernaut-0.1.40-py3-none-any.whl/kubernaut/cli.py", line 99, in save_config
    json.dump(config_data, cf, indent=2)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```

Missing a `.encode('utf-8')` somewhere, maybe? Kubernaut 0.1.39 seems OK here.

**Comment by plombardi89** [comment]
should be fixed now in 0.1.44
