### ISSUE TITLE
`kubernaut claims` fails

### ISSUE THREAD

**Issue by concaf** [datawire/kubernaut#36]
Pretty sure I'm doing something wrong, but the error message does not point me anywhere :(

```
$ ./kubernaut claims create --name mycluster
Traceback (most recent call last):
  File "kubernaut/cli.py", line 47, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 27, in new_func
  File "kubernaut/claims/cmd.py", line 68, in create_claim
  File "kubernaut/claims/cmd.py", line 157, in _create_claim
AttributeError: 'NoneType' object has no attribute 'create_claim'
[27707] Failed to execute script cli
```

**Comment by containscafeine** [comment]
Created a backend with `./kubernaut config backend create backend`, whatever that did, but now I get another not very helpful error -

```
$ ./kubernaut claims create --name mycluster
RawBackendResponse(status_code=401, headers={'server': 'envoy', 'date': 'Wed, 15 Aug 2018 04:25:29 GMT', 'content-type': 'application/json', 'content-length': '98', 'x-envoy-upstream-service-time': '2'}, content={
  "code": "invalid_header", 
  "description": "Invalid header: Error decoding token headers."
}
, json={'code': 'invalid_header', 'description': 'Invalid header: Error decoding token headers.'})
Error: Unable to create claim!
```
