### ISSUE TITLE
Traceback when `claims delete <name>` is invoked and there is no backend defined. 

### ISSUE THREAD

**Issue by plombardi89** [datawire/kubernaut#39]
```venv/bin/kubernaut claims delete kat
[5667] Failed to execute script cli
Traceback (most recent call last):
  File "kubernaut/cli.py", line 47, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 27, in new_func
  File "kubernaut/claims/cmd.py", line 120, in delete_claim
AttributeError: 'NoneType' object has no attribute 'delete_claim'
make: *** [cluster.yaml] Error 255```

**Comment by plombardi89** [comment]
Should be fixed by GH-40. Thanks @rhs
