### ISSUE TITLE
try to follow the manual. this is what i got

### ISSUE THREAD

**Issue by anatolyrossinsky** [datawire/kubernaut#47]
❱ kubernaut config backend create --url="https://next.kubernaut.io" --name="v2" --activate $TOKEN
Traceback (most recent call last):
  File "kubernaut/cli.py", line 47, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1134, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "kubernaut/cli.py", line 32, in cli
  File "kubernaut/config/model.py", line 72, in load
  File "pathlib.py", line 1189, in read_text
  File "pathlib.py", line 1176, in open
IsADirectoryError: [Errno 21] Is a directory: '/Users/anatoly/Library/Application Support/kubernaut/config'
[16789] Failed to execute script cli

**Comment by jachinte** [comment]
Same here
